services:
  front:
    image: todo-frontend
    build:
      context: ./todo-frontend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    container_name: todo-frontend # This will name the container
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
    container_name: todo-backend-mongo
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"] # Overwrite the CMD
    volumes: # Declare the volume
      - ./todo-backend/redis_data:/data
    container_name: todo-backend-redis
  back:
    image: todo-backend
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://todo-backend-redis:6379
      - MONGO_URL=mongodb://the_username:the_password@todo-backend-mongo:27017/the_database
    container_name: todo-backend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - front # wait for the frontend container to be started
      - back # wait for the backend container to be started
